### ISSUE TITLE
Todo-List for 'QZKS'

### ISSUE THREAD

**Issue by redapple0204** [redapple0204/my-boring-python#162]
## 期中倒计时2天（还有可复习的时间） //紧急复习阶段

所有科目基础复习完毕，现在正在刷题

我的宗旨是：学校作业重要的才写，没啥用的不写！

### 2.16（周四）-3.18（周六）
- [x] 适应新学期，放松。

### 3.19（周日）
- [x] 完成生物第一课练习
- [x] 完成地理第二课练习
- [x] 完成历史第二课练习
- [x] 完成数学第二单元复习

### 3.22（周二）
- [x] 搞完《与朱元思书》
- [x] 复习物理第二单元前两课
- [x] 复习生物第二课和第三课
- [x] 复习地理第二节和第三节

### 3.23（周三）
- [x] 搞懂英语的语法问题，并且做练习
- [x] 复习生物，地理后一节

### 3.26 （周日）
- [x] 生物写完第一章检测题以及第二章第一、二、三节

### 3.27（周一）
- [x] 物理写完第一张检测题以及摩擦力和第三章检测题

### 3.28（周二）
- [x] 地理写完第二章第一、二、三节以及第二章检测题
- [x] 进行英语第四课的预习

### 3.29（周三）
- [x] 地理往后写两节
- [x] 生物往后写两节

### 3.31（周五）
- [x] 写完一份数学试卷

### 4.2（周日）
- [x] 整理好作文素材
- [x] 弄好生地接下来的复习题目等
- [x] 下午复习体育

### 4.3（周一，但休假）
- [x] 再写一份数学试卷
- [x] 生物写完第三章
- [x] 语文弄完第二篇古文，顺便复习第一篇
- [x] 把前几天的数学题搞懂
- [x] 复习上学期学的政区图并且做期中测试（1），然后继续做珠江三角洲和长江三角洲然后自学长株潭并且做完它的练习然后再做那个单元的单元测试然后接下来自学北京并且做完第一节的内容
- [x] 语文弄完第三篇古文

### 4.4 （周二，但休假）
- [x] 复习地理台湾和新疆和贵州和黄土高原然后做自学第九章再做第八，九章测试题。
- [x] 语文背会那五首课内古诗词，并且流利的默写。然后再弄后面一篇古文
- [x] 生物做完期中测试卷（1）（2）
- [x] 搞数学

### 4.5（周三）
- [x] 语文开始弄课外古诗词

### 4.6（周四）
- [x] 数学做一份卷子
- [x] 生物写一份期末测试卷
- [x] 地理写期末测试卷（1）

### 4.7（周五）

暂无计划，写作业

### 4.8（周六）
- [x] 数学写一份试卷，并且讲完
- [x] 历史写完所有到期中考试的内容
- [x] 物理写五三第九单元测试，轻松夺冠第八，第九单元
- [x] 历史复习完所有内容，
- [x] 物理写一套期中测试

### 4.9（周日）
- [x] 生物往后写完第一章全部，并且写一份期中测试题
- [x] 地理写一份上学期的测试题
- [x] 语文搞完文学常识、字词读音以及诗词默写等，有时间写一些现代文
- [x] 数学写一份试题，讲完

### 4.10（周一）
- [x] 完成生物期末复习题
- [x] 完成地理期末复习题
- [x] 完成数学期中复习题
- [x] 完成物理期中复习题

### 4.11（周二）
- [x] 再次强化语文古文，古诗，读音，文学常识，**阅读**
- [x] 完成英语期中复习题
- [x] 完成历史期中复习题
- [x] 完成物理期中测试题 **重要**

### 4.12（周三）
- [x] 看部分科目的错题
- [x] 再次强化物理

### 4.13（周四）
- [x] 完成语文的一到二单元的文学常识阅读，再次查看语文古文中错误的字词还有整句翻译，然后背《海底两万里》的知识。
- [x] 完成数学一份
- [x] 完成历史的一大堆题目
- [x] 完成各科的一些指定题目

### 4.14（周五）
- [x] 写一份数学题
- [x] 如果有可能做语文的阅读题
- [x] 背语文的《海底两万里》内容
- [x] 完成一份语文卷子

### 4.16（周六）
- [ ] 完成数学一份，并且做梳理
- [ ] 最后复习语文一次，完成一份全真模拟试题
- [ ] 整理完全科错题，然后寻找不会的地方巩固
- [ ] 完成生物，地理两份题目，然后完成地理上学期的复习题两份
- [ ] 完成历史两份试卷
- [ ] 完成物理两份试卷
- [ ] 完成英语两份试卷，做好作文的复习

### 4.17（周日）
- [ ] 完成数学试卷一份，整理一份“提纲”
- [ ] 完成生物地理各一份，查缺补漏
- [ ] 完成英语两份
- [ ] 完成历史一份
- [ ] 完成物理一份
- [ ] 完成再次查看语文

**Comment by lizongzeshunshun** [comment]
# TO-DO

## 语文

- [ ] 复习所有诗歌
- [ ] 复习古文

## 数学

暂无计划。

## 英语

暂无计划

## 物理

- [ ] 做完“十大难题”
- [ ] 多刷中难度题目

## 历史

背背背

## 地理

- [ ] 做练习册
- [ ] 复习书

## 生物

- [ ] 刷题

**Comment by redapple0204** [comment]
@lizongzeshunshun 这三天我要复习炸了。。。。

**Comment by lizongzeshunshun** [comment]
你们啥时候考

**Comment by redapple0204** [comment]
@lizongzeshunshun 17.18，不参加统考
你们呢

**Comment by lizongzeshunshun** [comment]
20

**Comment by redapple0204** [comment]
擦，为什么那么好......
我这里复习好紧张啊

**Comment by redapple0204** [comment]
感觉现在复习很紧张啊，。。
另外按理说我们的时间是跟你们的一样的啊....这次怎么搞的

2017-04-07 21:05 GMT+08:00 LIZONGZE <notifications@github.com>:
