### ISSUE TITLE
Todo-List for "期末考试"

### ISSUE THREAD

**Issue by redapple0204** [redapple0204/my-boring-python#226]
### 5.3（周三）
- [x] 写完生地第一章（单元）综合检测题
### 5.4（周四）
- [x] 复习物理“浮力”部分
### 5.7（周日）
- [x] 写英语U6综合测试题
### 5.8（周一）
- [x] 做一份语文的训练

### 5.9（周二）
- [x] 写地理后一章，生物后一章
- [x] 复习一下物理

### 5.10（周三）
- [x] 完成英语基础语法部分的练习

### 5.13-5.14（周六-日）
- [x] 完成所有岳阳楼记的翻译考察
- [x] 完成生地计划
- [x] 完成数学最后一单元检测卷一份

### 5.15-5.19（周一到周五）
- [x] 完成语文所有课内古诗词的背诵
- [x] 背完小石潭记，并且完成翻译
- [x] 完成生物到第四单元前
- [x] 完成地理到第五章认识大洲

### 5.20-5.21（周六-周日）
- [x] 完成生地复习七下
- [x] 弄语文的小石谭记

### 5.22（周一）
- [x] 往后背一篇古文 PART1
- [x] 真正弄完生地七下所有内容（彻底弄清楚），然后做七下生物，地理测试题x2

### 5.23（周二）
- [x] 弄地八上前两章
- [x] 穿插着复习地理七年级下册（滚动复习，使用的复习方法：看金卷的填空题，然后不会的看后面的答案，然后填写上去）的第一，二章

### 5.24(周三）
- [x] 复习生地八上ALL，并且做期末测试题x2
- [x] 找错题

### 5.25(周四）
- [x] 复习生地八下第一章，如果昨天有未完成的继续完成

### 5.26（周五）
- [x] 复习生地八下ALL，并且做测试题

### 5.27（周六）
- [x] 没有复习计划，做作业

### 5.28（周日）
- [x] 复习生地所有,并且做会考试题x1查看复习情况
- [x] 复习完所有的物理（最后一章除外）
- [x] 开始生物刷题第二轮（做完讲学稿五）
- [x] 地理着重复习七下全部！！！
- [x] 把语文最后一篇古文背完

### 5.29（周一，但放假）
- [x] 复习完所有的语文
- [x] 数学复习

### 5.30(周二，但放假）
- [x] 背完地理七下提纲
- [x] 数学第二单元

### 5.31（周三）
- [x] 刷生物5-10练习，地理七下练习

### 6.3（周六）
- [x] 完成生物会考模拟题x1，然后找出缺漏的地方。
- [x] 完成邦德地理七下的所有题目，然后找出缺漏的地方，做邦德的题目七，八讲
- [x] 完成物理后两章复习

### 6.4（周日）
- [x] 刷完邦德的所有地理，然后再做一份2015的题，继续查缺补漏
- [x] 复习完物理ALL
- [x] 做一份数学题

### 6.5（周一）
- [x] 刷完语文的默写

### 6.7（周三）
- [ ] 查看语文错误的字
- [ ] 完成生物到50页
- [ ] 完成地理到70多页
- [ ] 背诵历史提纲1-10课，然后考察

### 6.8（周四）
- [ ] 完成物理最后一单元测试B卷
- [ ] 完成生物到75页
- [ ] 完成地理一个会考模拟题，然后查缺补漏

### 6.9（周五）
- [ ] 完成学校作业

### 6.10（周六）
- [ ] 完成英语的1-4课复习，相应的刷题，看作文范文
- [ ] 完成历史的所有背诵任务
- [ ] 重新复习语文的所有内容
- [ ] 数学讲上一章的错误，然后做新的一章
- [ ] 下午做锻炼（属于体育复习）

### 6.11（周日）
- [ ] 完成英语5-8课复习，相应的刷题，看范文
- [ ] 刷历史1-10课题目
- [ ] 刷物理第一，二单元的B试卷
- [ ] 刷生物75-150页
- [ ] 刷地理x2，查缺补漏

### 6.12（周一）
- [ ] 刷生物150-200页
- [ ] 刷地理试卷x1

### 6.13（周二）
- [ ] 刷生物地理试卷各一套，然后查缺补漏
- [ ] 刷历史11-15课题目
- [ ] 刷数学最后一个单元的题目

### 6.14（周三）
- [ ] 刷生物地理试卷各一套，然后查缺补漏
- [ ] 刷物理第三单元B试卷

### 6.15（周四）
- [ ] 刷英语培训书的试卷一套，然后查看错误 **英语复习完毕**
- [ ] 刷历史全部

### 6.16（周五）
- [ ] 完成学校作业

### 6.17（周六）
- [ ] 完成物理第四单元，第五单元的B卷。
- [ ] 完成生物，地理试卷x3，然后查缺补漏
- [ ] 完成语文的重检测，然后完成语文花开的翻译检测ALL，然后查看文学常识，字音等
- [ ] 体育考试锻炼复习

### 6.18（周日）
- [ ] 完成语文的作文提纲整理
- [ ] 完成物理第六单元B卷
- [ ] 完成数学独家期末复习
- [ ] 完成生物，地理试卷x2，然后查缺补漏

### 6.19（周一） **体育考试**
- [ ] 完成历史期末测试卷x1（可调换到6.18进行）
- [ ] 完成生地刷题x1
- [ ] 完成物理期末测试题x1

**Comment by lizongzeshunshun** [comment]
# 生物

- [ ] 复习植物结构
- [ ] 概览
- [ ] 购买从初一到初二所有《双成卷王》
- [ ] 第一波刷题
- [ ] 购买所有《五年中考三年模拟》
- [ ] 第二波刷题

# 地理

- [ ] 恶补初一内容
- [ ] 概览
- [ ] 更详细的记忆（所有）
- [ ] 双成卷王 刷题Round1
- [ ] 五三 刷题Round2


## Do not go gentle into that good night.
## Never give up and you'll be successful.

**为努力的自己致敬！**

**Comment by redapple0204** [comment]
@lizongzeshunshun WTF？？？？？
我点击编辑我的东西，结果怎么没有任何提示你的就不见了？？？？？？？

**Comment by redapple0204** [comment]
然后所有东西都无法编辑...

**Comment by redapple0204** [comment]
是不是bug了...我怎么换浏览器换手机都不行

**Comment by lizongzeshunshun** [comment]
我去

**Comment by redapple0204** [comment]
@lizongzeshunshun 谢天谢地，我还好开了backhub的定时备份
以下是原内容

**更详细的计划会以Word和Excel文档展现（暂未做好）**

# 生物【会考】

- [ ] 复习植物结构
- [ ] 概览
- [ ] 购买从初一到初二所有《双成卷王》
- [ ] 第一波刷题
- [ ] 购买所有《五年中考三年模拟》
- [ ] 第二波刷题

# 地理【会考】

- [ ] 恶补初一内容
- [ ] 概览
- [ ] 更详细的记忆（所有）
- [ ] 双成卷王 刷题Round1
- [ ] 五三 刷题Round2

# 物理【期末测试】

- [ ] 找点难题做

# 历史【期末测试】

- [ ] 每天一记【一课】

# 数学【期末测试】

- [ ] 找点难题做

# 英语【期末测试】

- [ ] 买本阅读书
- [ ] 练习写作文

## Do not go gentle into that good night.
## Never give up and you'll be successful.

**为努力的自己致敬！**

**Comment by lizongzeshunshun** [comment]
# 地理 News

**《初中学业水平考试》新的进度 **

** 30Pages / 146Pages = 20.54% **

![default](https://cloud.githubusercontent.com/assets/10304206/26157904/f9be96d6-3b4c-11e7-84e1-89538d6efcf0.png)

**Comment by lizongzeshunshun** [comment]
# 地理 News

**《初中学业水平测试》新的进度**

**45Pages / 146Pages = 30.82%**

![image](https://cloud.githubusercontent.com/assets/10304206/26205193/9fa69898-3c13-11e7-85ce-dc33f9548774.png)

**Comment by lizongzeshunshun** [comment]
# Project VMax

**会考、期末考的最后一个计划**

## 生物

- [ ] 写完练习题
- [ ] 搞懂植物的结构

## 地理

- [ ] 写完册
- [ ] 写完卷
- [ ] 针对性看地图、刷题
- [ ] 了解缺陷

## 数学

- [ ] 每晚压轴题

**Comment by redapple0204** [comment]
@lizongzeshunshun 最后一周了啊.....

**Comment by lizongzeshunshun** [comment]
@redapple0204  是啊

**Comment by lizongzeshunshun** [comment]
# 测试

会考模拟：2014年学业测试试卷

## SCORE: 97.00/100.00

## 生物

分数 **50.00 / 50.00**

## 地理

分数 **47.00/50.00**

**Comment by lizongzeshunshun** [comment]
# Days Plans - (2017-06-24)

## 7:00-10:00

去公园散步+休息

## 10:00-12:00

看、复习好目前所有错题

## 13:00-15:00

看地理书

## 15:00-19:00

自行测试

**Comment by lizongzeshunshun** [comment]
# Days Plans - (2017-06-26)

## 7:00-8:00

进行一遍地理Checklist校核（完整校核，No.0-No.100）。

## 8:30-9:30

查一查生物、地理的奇淫题目，主要做生物题目。

##  10:00-11:00

再次进行一遍地理Checklist校核（完整校核，No.0-No.100）。

## 11:00-12:30

吃中饭+睡觉

## 12:30-13:15

1. 看看QQ群里的内容，保持心情冷静、沉着、从睡觉中清醒过来。
2. 看看生物、地理的错题。

## 13:30

去学校。

## 13:45-14:15

进行地理Checklist快速校核（主要集中算力在No.50-No.100）。

## 14:15-14:30

停下一切工作，保持冷静、加强自信（Don't think anything）

## 15:00-16:00

# JUST DO IT

**Comment by redapple0204** [comment]
## 6.26（周一） **生地会考**

本计划**不会**被打印

### 计划总体安排
暂无

### 7：00-8：00
起床，刷一份生地会考模拟题

### 8：00-9：00
吃饭

### 9：00-11：00
看生物地理的《初中学业水平考前必备小册》，使用瞬时记忆记下一些实在记不住的东西，顺便看看地理的政区图还有铁路分布图，集中火力看生物的。

### 11：00-12：00
吃饭

### 12：00-13：00
随便翻翻资料，上Q群看看大家的活跃程度，然后和组员聊会天之类的

### 13：00-13：20
去学校

### 13：20-13：40
看看考场位置，然后尽力放松

### 13：40-13：50
放松，和~~基友~~聊会天

### 13：50-14：30
放松，看《初中学业水平考前必备小册》，以及背不下来的东西真的抢记

### 14：30-15：00
全力放松，不要向任何东西，不要直视老师的脸或者窗外，最好想想考完要干啥

### 15：00-16：00

# JUST DO IT ,EVERYTHING WILL BE DONE.

### 16:00-22：00
写周末作业

**Comment by lizongzeshunshun** [comment]
@redapple0204 
话说你有什么模拟卷吗，我都没卷子做了

**Comment by redapple0204** [comment]
@lizongzeshunshun 多的很！，你要难度如何的？

**Comment by lizongzeshunshun** [comment]
@redapple0204 中等偏低

**Comment by redapple0204** [comment]
@lizongzeshunshun Q上已回复

**Comment by lizongzeshunshun** [comment]
@redapple0204 话说你有没有数学的难题（填空压轴、选择压轴或者应用压轴）

**Comment by redapple0204** [comment]
@lizongzeshunshun 别急，我要问我妈，预计今明两天能恢复

**Comment by lizongzeshunshun** [comment]
@redapple0204 好的

**Comment by lizongzeshunshun** [comment]
# 复习计划备份

[Project Holy-Review Full Plans Text.pdf](https://github.com/redapple0204/my-boring-python/files/1114742/Project.Holy-Review.Full.Plans.Text.pdf)
